### PR TITLE
Add vellum

### PR DESCRIPTION
**Pull request by cole-sanderson**
- Stencil is now built on top of Vellum. 
- Fixed Alert component to work with Vellum
- Cleaned up styles in fixtures because we are using Vellum styles now

Status: Opened for Review
Reviewers: @kpeatt @jeffkamo @ry5n @avelinet
JIRA: ?

### CODE REVIEW

**Comment by cole-sanderson** [comment]
Updated button component from vellum button width fix

**Comment by kpeatt** [comment]
@cole-sanderson Made some updates here but this is looking good. GtM from me!

**Comment by cole-sanderson** [comment]
@kpeatt looks good.

**Comment by jeffkamo** [comment]
:+1:

**Comment by nastiatikk** [comment]
NOTE: [PR-110](https://github.com/mobify/stencil/pull/110) dependent on this branch. Please don't remove it untill **Tabs** branch is merged to master.

**Pull request merged**
