### PR TITLE
iOS6 icon component fix

### PR DESCRIPTION
**Pull request by nastiatikk**
iOS6 fix when we have several different icons in a row but device shows them all identical

Status: **Ready to review**

Reviewers: @cole-sanderson @jeffkamo @avelinet @ry5n @mlworks @kpeatt 

screenshot 2015-02-12 17 44 26

### CODE REVIEW

**Comment by kpeatt** [comment]
How does this fix work?

**Comment by nastiatikk** [comment]
Magically. It's seems to be iOS6 unexplainable bug that is fixed with min-width property with no logic (at least I can't see any). Min-width can be any px (1px, 0px, 20px, etc.)

I've updated top comment with the screens

**Comment by nastiatikk** [comment]
Two screens from icon stencil components (with and without min-width)

**Comment by kpeatt** [comment]
What the :hankey:.

Nice find.

**Comment by jeffkamo** [comment]
As a future fix, we may want to set to `min-width: 0`, which apparantely also works. Low priority thing though.

**Comment by kpeatt** [comment]
I'd make a PR for that so we don't lose that. Good enhancement.

**Pull request merged**
