### PR TITLE
Dust renaming and index template

### PR DESCRIPTION
**Pull request by nastiatikk**
Updates:
* `*.dust` files don't have underscore in the filename as there is no need for it.
* `index.html` template added to the **/templates** folder.

Status: **Ready for Review**

Reviewers: @jeffkamo @avelinet @ry5n @mlworks @kpeatt @cole-sanderson

### CODE REVIEW

**Comment by kpeatt** [comment]
@nastiatikk what's the goal of this?

**Comment by nastiatikk** [comment]
@kpeatt consistency
* **Dust** templates don't need _ in the filename. It was used to detach visually partials from components, but then partials were moved to its own folder.
* **index.html** is a template for /test folder to start from

**Comment by ry5n** [comment]
I agree we don’t need the underscore in front of template filenames.

As far as adding the index.html, this is a template for the component’s test html. The trouble is that with the current folder structure, the tests live separately, so the name and placement here doesn’t mirror the rest of the repo, and could be confusing. I think we should move it to `template/tests/visual/index.html` and add `templates/tests/visual/template.scss`.

**Comment by nastiatikk** [comment]
In this case we also need to create a `/template` folder in the `/dist` folder and remove `/template` from the root directory. 

From the other side this folder (by name) contains all templates. There are not many of them to get confused. And in the documentation (that hopefully will be merged soon) you'll see each file destination.

I'm fine with any of these solutions.

**Comment by ry5n** [comment]
No, we don’t want scaffolding in `dist`. What I mean is instead of `index.html` right inside `templates`, move it to `templates/tests/visual/` so that it’s clear what it’s for. It’s not perfect, but until we have each component in a separate repo I think it’s a good compromise.

**Comment by nastiatikk** [comment]
Hm… I can't agree. For me it looks much more complicated. If we do this we also should move scss and dust files to `/templates/dist/components` and `/templates/dist/utils` (even if they're the same) what becomes super complicated. And if we move just test files to its own folder it won't be consistent and will be confusing.

**Comment by ry5n** [comment]
I see what you mean, but I agree I don’t want to do that either. We definitely need some way of clarifying what `index.html` is though. I’d be happy for now if we just put it in `templates/tests/`.

**Comment by nastiatikk** [comment]
@ry5n Will it be more clear with these instructions? What do you think? 
https://github.com/mobify/stencil/pull/123

**Comment by ry5n** [comment]
That will definitely help. I still think we should at least have scaffolding for tests in their own subfolder. It’s not a big change from what you have.

**Comment by jeffkamo** [comment]
@nastiatikk: So for now can we put `index.html` in `/tests`? We can flesh out the test directory structure later. But in the mean time, let's not block #123

**Comment by nastiatikk** [comment]
Can we for now leave it in the `/template` folder? https://github.com/mobify/stencil/pull/123 instructions use `/template` folder structure, not `/template/tests/visual`

**Comment by jeffkamo** [comment]
sure

**Pull request merged**
