### PR TITLE
Progress Bar Component

### PR DESCRIPTION
**Pull request by nastiatikk**
Visual *'Progress is'* is a part of u-hidden utility that is not included to Stencil. It's an accessibility solution (cause aria-label doesn't work for some reason) to define what is this % about. p

Please review this component and leave your notes.
Meanwhile I am gonna work on the dust file for this component.

## Todo

- [x] Remove c--radius and c--round variations
- [x] Remove the visual label (keep the accessible label)
- [x] Consider minimizing the configurable variables
- [x] Add a Table of Contents link to Progress Bar Component in root Readme file
- [x] Designer +1 @ry5n
- ~~Designer +1~~ (close enough!)

### CODE REVIEW

**Comment by nastiatikk** [comment]
@jeffkamo @avelinet @cole-sanderson @ry5n @kpeatt @mlworks

**Comment by avelinet** [comment]
@nastiatikk I made some minor changes to the visual tests wording, mostly just grammar stuff :)

**Comment by nastiatikk** [comment]
Thank you @avelinet!

**Comment by ry5n** [comment]
This is good work. There are some things I’d suggest changing, my first thought is that I haven’t seen us implement this component on a build before. Have we done it? Should it be a priority?

**Comment by nastiatikk** [comment]
We had some kind of progress on Carnival project but because of its design we needed to use a desktop logic and approach. Otherwise I haven't seen it in any of our projects. So I'd say that priority for this component is minor. 

Though I'll be happy to hear your ideas and implement them.

**Comment by ry5n** [comment]
Thanks for the input. Let’s hold off on this for the moment. I’ll loop back sometime within the week.

**Comment by ry5n** [comment]
So here are my suggestions:

- Let’s remove the `c--radius` and `c--round` variations. Let’s keep things simpler (devs can customize appearance in their projects)
- I don’t think the label will be flexible enough to style (it has no element wrapper). Let’s leave the visual label out for the simplest version
- I think we have too many configurable variables. We definitely don’t need font-size, spacing or the radius/round variables. I think height, color and background color are all we really want and we could even get away with none.

**Comment by nastiatikk** [comment]
* Removed `c--radius` and `c--round`. 
* I would keep the label. It's a valuable piece of a progress-bar and it's not a big deal to wrap it with a `span` tag. Otherwise if the label required how it's gonna be added to the component if there is no element in the markup for that?
* Removed label colour and font-size

**Comment by nastiatikk** [comment]
I've made all requested changes. Still think that label should be kept as a valuable piece of a progress bar. 

Can be reviewed again.

**Comment by jeffkamo** [comment]
Might want to pull from master. Looks like there's a conflict just waiting to be resolved.

**Comment by jeffkamo** [comment]
@nastiatikk is that last to-do still need to be done?

**Comment by nastiatikk** [comment]
No @jeffkamo It's already removed and kept for accessibility reason only

**Comment by ry5n** [comment]
I think this is good to go in. We should take another look when we migrate to Stencil 2.0.

**Pull request merged**
