### PR TITLE
Update Readmes of Progress Step component

### PR DESCRIPTION
**Pull request by avelinet**
Just some quick updates to the Readmes for the Progress Step component that got missed in the excitement to get it merged in 😯

Status: **Ready to Merge**

Reviewers: **@nastiatikk @ry5n @jeffkamo**

### CODE REVIEW

**Comment by ry5n** [comment]
+1

**Comment by nastiatikk** [comment]
For better readability highlight with bold **background color** and other options in the list of options?

Otherwise +1

**Comment by avelinet** [comment]
@nastiatikk good suggestion but then it wouldn't be consistent with other Readmes where those options are not highlighted. Could open an issue to highlight them all?

**Comment by nastiatikk** [comment]
Probably yes, changing all readmes to make them more readable

**Pull request merged**
