### PR TITLE
Testing instructions readme

### PR DESCRIPTION
**Pull request by cole-sanderson**
I had hard time to work with components locally, when I followed the steps from https://github.com/mobify/stencil/issues/66 and I finally figured out. I thought it will be good idea to include to README.

### CODE REVIEW

**Comment by jeffkamo** [comment]
@ry5n any objections to this being merged in? All of Kyles points appear to be have dealt with.

**Comment by jeffkamo** [comment]
This looks good to me

**Comment by nastiatikk** [comment]
@cole-sanderson would you mind to add couple words how to structure files? Which folders and where you should create (in the /tests and in the /dist) and how you need to structure CSS in the test files with @import. Or it's a useless information?

**Comment by jeffkamo** [comment]
There is a template folder that shows all of the required files. However, we don't have any examples or demonstrations of exactly what test files are needed.

A new PR should be created to expand on these details.

**Comment by ry5n** [comment]
This is good to merge for now. As a follow-up. I’d like to see the Testing section changed to Contributing, and put the contents of this and the Updating github pages section inside, maybe move some stuff around in there.

**Comment by nastiatikk** [comment]
Ok, I will update these instructions in another PR. Template folder is not enough I think, it's just 1 folder structure and no information about tests and imports

**Comment by ry5n** [comment]
@nastiatikk Agreed.

**Pull request merged**
