### PR TITLE
Stencil readme update

### PR DESCRIPTION
**Pull request by nastiatikk**
Status: **Ready for Review** 
Reviewers: @kpeatt @mlworks @ry5n @avelinet @cole-sanderson @jeffkamo @yourpalsonja 

## Changes
- Warnings added on top of `README`

These are very important rules that all who work with Stencil should know. If we keep them somewhere at the bottom of the page there is a high change for people not notice them. Especially if these are the people who work on Stencil for a while - they simply don't check `README` anymore.

## Todos:
- [x] Designer +1
- [ ] Designer +1

### CODE REVIEW

**Comment by jeffkamo** [comment]
:+1:

**Comment by jeffkamo** [comment]
Ignore the irony in my typo fix commit message.

**Comment by ry5n** [comment]
@jeffkamo @nastiatikk @kpeatt I missed that this got merged. I just want to say I don’t think these warnings belong at the top of the readme. Really there should be a top-level section called “Contributing” and yeah put these warnings right at the top of that section but they don’t belong at the top of the file which should speak to end users not maintainers.

Also I don’t think we need to:
- warn people not to commit to master
- tell people how to open PRs

I’m not saying we don’t share that knowledge but specific project readmes are not the place to document general git practices. The only warning we really needed to surface better was the one about gh-pages.

**Comment by nastiatikk** [comment]
I agree that we need to move it down to Contribution section. But still think we need to mention to create PR only from master branch to avoid cases happened with TAB branch when its parent branch was removed

**Comment by avelinet** [comment]
Maybe rather than include git etiquette/best practices in our readmes it could simply be something that @ry5n touches on in the Stencil workshop he's been talking about putting on?

**Comment by ry5n** [comment]
Yup we could totally do it there.

**Comment by nastiatikk** [comment]
What was there? I don't remember Stencil workshop

**Comment by ry5n** [comment]
Hasn’t happened yet! Something I’d like to do soon. :)

**Pull request merged**
