### PR TITLE
Gh pages documentation tweak

### PR DESCRIPTION
**Pull request by nastiatikk**
Status: **Ready for Review** 
Reviewers: @jeffkamo @ry5n @avelinet @tedtate 

## Changes
- Documentation updated with TODO instructions when you directly committed to `gh-pages` branch

## Todos:
- [x] Designer +1 @ry5n
- [x] Designer +1 @jeffkamo

### CODE REVIEW

**Comment by ry5n** [comment]
+1

**Comment by tedtate** [comment]
I'm a little confused by these instructions. What do we mean by `remove github-pages branch`?

**Comment by nastiatikk** [comment]
@tedtate Ops, will it be clearer if it's said `delete`?

**Comment by jeffkamo** [comment]
Might help to clarify by saying you must delete the `gh-pages` branch from the Github repo (or even more specifically, from remote `origin`)

**Comment by tedtate** [comment]
Okay, but if you already have the commits which broke the branch locally, you are going to end up right in the same place...

**Comment by nastiatikk** [comment]
@tedtate I think I need to clarify the instructions more. Generally if you pushed a commit you need to revert this commit, then you need to push this revert, then you need to delete a branch and then you need to run `git push origin gh-pages` what will also publish the branch. If you don't remove the branch and run `git push origin gh-pages` it will run with errors.

**Comment by jeffkamo** [comment]
@tedtate @nastiatikk not quite. This documentation is __not__ to clarify how to fix a broken `gh-pages` branch. Rather, it explains how to fix the broken `git subtree split --branch gh-pages --prefix tests/` command, which breaks when you commit directly to `gh-pages`.

**Comment by nastiatikk** [comment]
Oh right. With only exception it fixes `git push origin gh-pages` command

**Comment by jeffkamo** [comment]
+1

**Pull request merged**
